services:
  postgres:
    image: postgres:latest
    container_name: os-container
    environment:
      POSTGRES_DB: osDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2

volumes:
  postgres_data: